### ISSUE TITLE
Files support .xcf? 

### ISSUE THREAD

**Issue by AlvesR0** [WinMerge/freeimage#11]
Hi everyone. The FreeImage has file support. xcf(import / export)? If no. Is there a possibility to implement?

Alvesr.

**Comment by sdottaka** [comment]
FreeImage probably does not support .xcf.

This repository is simply a clone of FreeImage and is not official.

Please submit it to https://sourceforge.net/p/freeimage/.

**Comment by AlvesR0** [comment]
> O FreeImage provavelmente não oferece suporte a .xcf.
> 
> Este repositório é simplesmente um clone do FreeImage e não é oficial.
> 
> Envie-o para https://sourceforge.net/p/freeimage/ .

I asked on the official forum. Days ago. no one answer. A lack of education. Thank you so much for replying. @sdottaka  : )
