### ISSUE TITLE
Doesn't compile with C++17 and higher because of auto_ptr

### ISSUE THREAD

**Issue by AdmiralPellaeon** [WinMerge/freeimage#12]
Hi,

the current project doesn't compile in C++17 or 20 becaue of deprecated stuff. auto_ptr was removed and throw(...) is also deprecated. Would be good to adapt the specific files.

Best regards

**Comment by sdottaka** [comment]
This repository is just a clone of FreeImage and is not official.

Please submit to https://sourceforge.net/p/freeimage/.
