### ISSUE TITLE
Fix for building FreeImage on MacOS 12

### ISSUE THREAD

**Issue by bferguson3** [WinMerge/freeimage#13]
Add the following includes and define to the given sub-source files:

ZLib/gzlib.c 
+#include <unistd.h>

ZLib/gzread.c 
+#include <unistd.h>

ZLib/gzwrite.c 
+#include <unistd.h>

LibJXR/image/decode/segdec.c 
+#include <libkern/OSByteOrder.h>
+#define _byteswap_ulong(x) OSSwapInt32(x)
+#define _byteswap_uint64(x) OSSwapInt64(x)

LibJXR/jxrgluelib/JXRGlueJxr.c 
+#include <wchar.h>

**Comment by sdottaka** [comment]
Thank you for the report.

However, this repository is just a clone, not the FreeImage main repository.

Please submit the patch to https://sourceforge.net/p/freeimage/patches/
