### ISSUE TITLE
Having trouble building the project

### ISSUE THREAD

**Issue by A-G-U-P-T-A** [WinMerge/freeimage#18]
Hi All,

I am getting the following error when building the library.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	jpeg_simple_progression already defined in jpeg.lib(jpeg62.dll)	FreeImage	C:\Projects\freeimage\LibJPEG.lib(jcparam.obj)	1	
Error	LNK2005	jpeg_set_defaults already defined in jpeg.lib(jpeg62.dll)	FreeImage	C:\Projects\freeimage\LibJPEG.lib(jcparam.obj)	1	
Error	LNK2005	jpeg_set_quality already defined in jpeg.lib(jpeg62.dll)	FreeImage	C:\Projects\freeimage\LibJPEG.lib(jcparam.obj)	1	
Error	LNK2005	jpeg_destroy already defined in jpeg.lib(jpeg62.dll)	FreeImage	C:\Projects\freeimage\LibJPEG.lib(jcomapi.obj)	1	
Error	LNK1169	one or more multiply defined symbols found	FreeImage	C:\Projects\freeimage\x64\Release\FreeImage.dll	1	

Am I doing something incorrectly that is leading to this ?

**Comment by sdottaka** [comment]
How do you build FreeImage?
If you have Visual Studio, please build using FreeImage.vs2022.sln, FreeImage.vs2019.sln, etc.

**Comment by A-G-U-P-T-A** [comment]
Hi I used VS 2022 FreeImage.vs2022.sln used the mentioned method. The message I am mentioning happens on it from the master branch. The FreeImage module is selected (by default) and I am trying to build it.

**Comment by AdmiralPellaeon** [comment]
I downloaded the current master version of the repo. I opened the VS2022 sln and built 'FreeImage' and 'FreeImageLib' with VS 17.8.3, debug and release in 64bit. No problems at all. Perhaps a broken file in your download? or some weird configurations in VS?

**Comment by A-G-U-P-T-A** [comment]
I tried again taking a fresh clone from github and selecting 2022 and building it the 5 errors and a lot of warnings is still persistent.
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	jpeg_simple_progression already defined in jpeg.lib(jpeg62.dll)	FreeImage	D:\CleanDirectory\freeimage\LibJPEG.lib(jcparam.obj)	1	
Error	LNK2005	jpeg_set_defaults already defined in jpeg.lib(jpeg62.dll)	FreeImage	D:\CleanDirectory\freeimage\LibJPEG.lib(jcparam.obj)	1	
Error	LNK2005	jpeg_set_quality already defined in jpeg.lib(jpeg62.dll)	FreeImage	D:\CleanDirectory\freeimage\LibJPEG.lib(jcparam.obj)	1	
Error	LNK2005	jpeg_destroy already defined in jpeg.lib(jpeg62.dll)	FreeImage	D:\CleanDirectory\freeimage\LibJPEG.lib(jcomapi.obj)	1	
Error	LNK1169	one or more multiply defined symbols found	FreeImage	D:\CleanDirectory\freeimage\x64\Release\FreeImage.dll	1	

Unsure why this is happening. Worked once on my system however started failing in consecutive builds. Now I am not a C++ expert so maybe unable to pinpoint this but this is a persistent problem post the first build. My system is 64 bit as well. I re-verified if that was the case.

EDIT:- Build works with x86 selected both release and debug is working...

**Comment by AdmiralPellaeon** [comment]
Did you try to delete the folder with all temporary intermediate compiling data, so that VS is really doing a fresh new build? Sometimes this helps.

**Comment by A-G-U-P-T-A** [comment]
Uh not sure what is happening but I think I will stop my effort here. These 5 errors are recurring. x86 build works seamlessly but x64 somehow is failing every time. My use-case is covered since it will be cross compatible hopefully. So I don't mind the x86 build.

**Comment by sdottaka** [comment]
Maybe you installed jpeg62.dll using vcpkg or something like that?
If so, you may be able to build successfully by disabling vcpkg in the project properties window such as libjpeg.

**Comment by A-G-U-P-T-A** [comment]
Omg yes that was causing the conflict. I just deleted the local packages and it created the thing. Thanks a lot.
